// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi91wrxd7Ka0ewagpdJ3pBFjg2AsECDQs',
    appId: '1:814014166491:web:3aa80010535f0324e7a3fe',
    messagingSenderId: '814014166491',
    projectId: 'pantherapp010-1b674',
    authDomain: 'pantherapp010-1b674.firebaseapp.com',
    storageBucket: 'pantherapp010-1b674.appspot.com',
    measurementId: 'G-VKEKZGDSP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxfrv6YVOPS_Lo9R8ty677D11tQOd-6QE',
    appId: '1:814014166491:android:c4ca041316f53423e7a3fe',
    messagingSenderId: '814014166491',
    projectId: 'pantherapp010-1b674',
    storageBucket: 'pantherapp010-1b674.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIp38rUynKOqyHN0LJlJatSa-APsFpGR0',
    appId: '1:814014166491:ios:cc2f262402105db0e7a3fe',
    messagingSenderId: '814014166491',
    projectId: 'pantherapp010-1b674',
    storageBucket: 'pantherapp010-1b674.appspot.com',
    iosBundleId: 'com.example.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIp38rUynKOqyHN0LJlJatSa-APsFpGR0',
    appId: '1:814014166491:ios:cc2f262402105db0e7a3fe',
    messagingSenderId: '814014166491',
    projectId: 'pantherapp010-1b674',
    storageBucket: 'pantherapp010-1b674.appspot.com',
    iosBundleId: 'com.example.driver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi91wrxd7Ka0ewagpdJ3pBFjg2AsECDQs',
    appId: '1:814014166491:web:49c17b74193769bce7a3fe',
    messagingSenderId: '814014166491',
    projectId: 'pantherapp010-1b674',
    authDomain: 'pantherapp010-1b674.firebaseapp.com',
    storageBucket: 'pantherapp010-1b674.appspot.com',
    measurementId: 'G-954Z7MGKY7',
  );

}